/*
    页面加载时
*/
$(document).ready(function(){
    $("#email-addr").css("color","#2277d9");
    $("#file-alert").hide();
    $("#par-email").hide();
    $("#isic-name").hide();
    $("#isic-id").hide();
    $("#born-date").hide();
    $("#science-name").hide();
    $("#science-web").hide();
    $("#science-file").hide();
    $("#science-num").hide();
    $("#note").hide();
    $("#git-way").hide();
});

/*
    大学电子邮件地址注册方式
*/
$("#email-addr").click(function(){
    $("#email-addr").css("color","#2277d9");
    $("#isic-member").css("color","#777");
    $("#official-file").css("color","#777");
    $("#github").css("color","#777");
    $(".item").show();
    $("#par-email").hide();
    $("#file-alert").hide();
    $("#isic-name").hide();
    $("#isic-id").hide();
    $("#born-date").hide();
    $("#science-name").hide();
    $("#science-web").hide();
    $("#science-file").hide();
    $("#science-num").hide();
    $("#note").hide();
    $("#git-way").hide();
});
$(document).ready(function(){
    $("#stu").focus(function(){
        $("#edu-box").show();
    });
});
$(document).ready(function(){
    $("#tea").focus(function(){
        $("#edu-box").hide();
    });
});
$("#age-ask").change(function () {
    if($(this).is(':checked')){
        $("#par-email").show();
    }else{
        $("#par-email").hide();
    }
});
/*
    ISIC/ITIC成员注册方式
*/
$("#isic-member").click(function(){
    $("#email-addr").css("color","#777");
    $("#isic-member").css("color","#2277d9");
    $("#official-file").css("color","#777");
    $("#github").css("color","#777");
    $(".item").show();
    $("#par-email").hide();
    $("#file-alert").hide();
    $("#isic-name").show();
    $("#isic-id").show();
    $("#born-date").hide();
    $("#science-name").hide();
    $("#science-web").hide();
    $("#science-file").hide();
    $("#science-num").hide();
    $("#note").hide();
    $("#git-way").hide();
});
/*
    官方文件注册方式
*/
$("#official-file").click(function(){
    $("#email-addr").css("color","#777");
    $("#isic-member").css("color","#777");
    $("#official-file").css("color","#2277d9");
    $("#github").css("color","#777");
    $(".item").show();
    $("#par-email").hide();
    $("#file-alert").show();
    $("#isic-name").hide();
    $("#isic-id").hide();
    $("#born-date").show();
    $("#science-name").show();
    $("#science-web").show();
    $("#science-file").show();
    $("#science-num").show();
    $("#note").show();
    $("#git-way").hide();
});
$("#c1").change(function () {
    if($(this).is(':checked')){
        $("#p1").hide();
    }else{
        $("#p1").show();
    }
});
$("#c2").change(function () {
    if($(this).is(':checked')){
        $("#p2").hide();
    }else{
        $("#p2").show();
    }
});

/*
    Github注册方式
*/
$("#github").click(function(){
    $("#email-addr").css("color","#777");
    $("#isic-member").css("color","#777");
    $("#official-file").css("color","#777");
    $("#github").css("color","#2277d9");
    $(".item").hide();
    $("#git-way").show();
});